name: GH-build-DEV

# eventos disparadores 
on:
  push:
    branches: [ "main" ] # eventos disparadores en branch main
  workflow_dispatch: # permite ejecución manual desde GitHub

jobs:
  build:

    runs-on: ubuntu-24.04 # siempre explicitar la version del Sistema Operativo

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: | # 8.0.x son versiones LTS
            8.0.x  
            9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Read Secrets
      run: echo ${{ secrets.USUARIO }}
      
    - name: Enviar correo con DebugMail
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        npm init -y
        npm install nodemailer

        echo "const nodemailer = require('nodemailer');

        let transporter = nodemailer.createTransport({
          host: 'app.debugmail.io',
          port: 25,
          secure: false,
          auth: {
            user: '393f07f9-d8d1-47a7-b138-980fa0e04e17',
            pass: '51e4c50e-78dd-45b0-9e5f-1fee8a15cefb'
          }
        });

        transporter.sendMail({
          from: 'john.doe@example.org',
          to: '393f07f9-d8d1-47a7-b138-980fa0e04e17@debugmail.io',
          subject: '✅ GH-build-DEV ejecutado correctamente',
          text: 'El pipeline terminó correctamente.'
        }).then(() => console.log('Correo enviado'))
          .catch(err => console.error('Error al enviar correo:', err));
        " > send-email.js

        node send-email.js